#define syslog source
#source s_net { udp(ip(0.0.0.0) port(514)); };
source s_net {
    tcp(
     ip("0.0.0.0")
     port(514)
    );
    udp(
     ip("0.0.0.0")
     port(514)
    );
    syslog(
     ip("0.0.0.0")
    );
    unix-stream("/var/run/syslog-ng/syslog-ng.sock");
};

#create individual filters to match each of the role categories
filter f_meraki_urls { host( "192.168.0.1" ) and match("urls" value ("MESSAGE")); };
filter f_meraki_events { host( "192.168.0.1" ) and match("events" value ("MESSAGE")); };
filter f_meraki_ids-alerts { host( "192.168.0.1" ) and match("ids_alerted" value ("MESSAGE")); };

#filter f_meraki { host( "192.168.0.1" ); };

#define individual destinations for each of the role categories
destination df_meraki_urls { file("/var/log/meraki_urls.log"); };
destination df_meraki_events { file("/var/log/meraki_events.log"); };
destination df_meraki_ids-alerts { file("/var/log/meraki_ids-alerts.log"); };

#destination df_meraki { file("/var/log/meraki.log"); };	

#bundle the source, filter, and destination rules together with a logging rule for each role category
log { source ( s_net ); filter( f_meraki_urls ); destination ( df_meraki_urls ); };
log { source ( s_net ); filter( f_meraki_events ); destination ( df_meraki_events ); };
log { source ( s_net ); filter( f_meraki_ids-alerts ); destination ( df_meraki_ids-alerts ); };

#log { source ( s_net ); filter( f_meraki ); destination ( df_meraki ); };

